# Generated by Django 5.1.3 on 2024-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vheicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecategory',
            old_name='vehicle_img',
            new_name='category_img',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='renting_cost',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
