# Generated by Django 5.1.1 on 2025-01-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdetails_role'),
        ('vheicles', '0002_rename_vehicle_img_vehiclecategory_category_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('scooter', 'Scooter')], default='car', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('orderStatus', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vheicles.vehicle')),
            ],
        ),
    ]
