# Generated by Django 5.1.1 on 2025-01-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vheicles', '0003_vehicleorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleorders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vehicleorders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicleorders',
            name='phone',
        ),
    ]
