# Generated by Django 5.1.1 on 2025-01-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorders',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('scooter', 'Scooter')], default='car', max_length=255),
        ),
        migrations.AlterField(
            model_name='carorders',
            name='orderStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='Pending', max_length=255),
        ),
    ]
