# Generated by Django 5.1.1 on 2025-01-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_carorders_user_remove_carorders_vehicle'),
        ('vheicles', '0003_vehicleorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewapayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vheicles.vehicleorders'),
        ),
        migrations.DeleteModel(
            name='CarOrders',
        ),
    ]
